services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./www:/var/www/html

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
